### ISSUE TITLE
model missing

### ISSUE THREAD

**Issue by ketakachono** [quicksandznzn/HeadSwap#1]
i have:
- epoch_00190_iteration_000400000_checkpoint.pt
- epoch_20.pth
- BFM folder with files inside

Where to find:
- sr_cf.onnx
-  Blender-401-00012900.pth
- parsing.pth

???

**Comment by longswordinhand** [comment]
Have you found it now?

**Comment by ketakachono** [comment]
No, I haven't. Can you please update the download links inside process/download_weight.sh? Or upload them to google drive. Looking forward to it :)

**Comment by longswordinhand** [comment]
Me neither.

**Comment by quicksandznzn** [comment]
I don't have any of these models， But you can train the model from scratch，It just lacks weight

**Comment by quicksandznzn** [comment]
@longswordinhand @ketakachono

**Comment by longswordinhand** [comment]
> I don't have any of these models， But you can train the model from scratch，It just lacks weight

Thanks for your suggestions. What datasets are used for training? Thanks.

**Comment by quicksandznzn** [comment]
> 
I refer to these projects 

https://github.com/JackZhouSz/HeSer.Pytorch

https://github.com/keshav1990/HeadSwap

**Comment by quicksandznzn** [comment]
> > I don't have any of these models， But you can train the model from scratch，It just lacks weight
> 
> Thanks for your suggestions. What datasets are used for training? Thanks.


I refer to these projects 

https://github.com/JackZhouSz/HeSer.Pytorch

https://github.com/keshav1990/HeadSwap

**Comment by ketakachono** [comment]
I had this working already but forgot to backup the weights, so I'm not going to train the model from scratch when I had it working just fine. I don't believe nobody has the weights anymore.

**Comment by quicksandznzn** [comment]
> * Blender-401-00012900.pth

I tried to contact the author by email, and the author replied that the content had been privatized

**Comment by quicksandznzn** [comment]
> I had this working already but forgot to backup the weights, so I'm not going to train the model from scratch when I had it working just fine. I don't believe nobody has the weights anymore.

I tried to contact the author by email, and the author replied that the content had been privatized

**Comment by ketakachono** [comment]
lol

**Comment by longswordinhand** [comment]
Do you know where they are from? Which project?
sr_cf.onnx
Blender-401-00012900.pth
parsing.pth
Thanks.

**Comment by quicksandznzn** [comment]
> Do you know where they are from? Which project? sr_cf.onnx Blender-401-00012900.pth parsing.pth Thanks.

#1
